// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalculTotalPriceController from "./calcul_total_price_controller"
application.register("calcul-total-price", CalculTotalPriceController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
